name: asami_app
description: A Flutter Clean Architecture project with BLoC (Cubit)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  asami_client:
    path: ../asami_client
  serverpod_flutter: ^3.2.3
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.5
  responsive_framework: ^1.5.1
  go_router: ^17.1.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  common_utils2: ^1.0.0
  common_designs:
    path: ../../../../../packages/common_designs
  icons_launcher: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.10.5
  injectable_generator: ^2.12.0
  json_serializable: ^6.12.0
  freezed: ^3.2.5
  gpt_markdown: ^1.1.5

flutter:
  uses-material-design: true


